version: "3"

services:
  app:
    image: node:17.0.0-alpine
    user: node
    working_dir: /home/node
    entrypoint: node
    tty: true
    stdin_open: true
    ports:
      - 8000:8000
    volumes:
      - ./app:/home/node

  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongo-data:/data/db
    working_dir: /usr/local/sampleCollections

  server:
    image: node:alpine
    volumes:
      - ./server:/usr/local/server
    working_dir: /usr/local/server
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://root:password@mongo:27017/app?authSource=admin
      - DATABASE_URL=postgres://root:password@db/app
      - JWT_SECRET=secret
    ports:
      - 127.0.0.1:3000:3000
    command: npm start

  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=app

volumes:
  mongo-data: {}


